name: pullrequest on main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install, Build, Test, Publish demo

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          registry-url: 'https://registry.npmjs.org/'
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: App Demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.

      - name: App Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
